### ISSUE TITLE
Versions 10.11 and 10.12

### ISSUE THREAD

**Issue by igala** [samdmarshall/OSXPrivateSDK#15]
Is a newer version  available ?

**Comment by csekel** [comment]
You can create them and follow samdmarshall spec's from the SDKsettings within each.

I've built my own after building/updating Darwinbuild and created sdk from all the headers from within  the plist I've created from what Apple provided.

**Comment by csekel** [comment]
Here's the latest Darwin SDK created from OS Apple 
https://github.com/PureDarwin/Darwin-15.6-SDK

**Comment by shinvou** [comment]
@csekel I'd love to see the 10.13 Private SDK. Also, why don't you create a Pull Request and let 10.11 and 10.12 be merged?

**Comment by Amar1729** [comment]
Found a pretty large repo of the sdks here:
https://github.com/phracker/MacOSX-SDKs

**Comment by matthewbauer** [comment]
All of the previously mentioned ones are the public SDK which I think you can easily get from Apple directly. What's useful about this repo is that it has some unreleased headers you can only get here (CoreFoundation/CFXPCBridge.h for instance).
